packages:
  - name: coinmate
    actions:
      - name: buy 
        runtime: nodejs:default
environment: $(
  PRIVATE_KEY
  PUBLIC_KEY
  CLIENT_ID
  SLACK_WEBHOOK_URL
  API_BASE_URL
  INVEST_API_BASE_URL
)
